### ISSUE TITLE
'earth-search-legacy.aws.element84.com' which cannot be resolved anymore

### ISSUE THREAD

**Issue by arjantenhoopen** [plant99/felicette#34]
L.S.
I can't get Felicette working anymore. It complains about 'earth-search-legacy.aws.element84.com' which cannot be resolved anymore.
Can you fix it? I really like to use felicette.

TIA,
Arjan

**Comment by plant99** [comment]
Whoops, thanks a lot for pointing it out! Turns out the `-legacy` in the url should be gone. 

Since, https://earth-search.aws.element84.com/v0 works, and I haven't explicitly mentioned this or the legacy URL in the project, I believe it's a default set in this particular version of `sat-utils`, I'll try updating it to a newer version and make a release soon.

**Comment by plant99** [comment]
Hey I've pushed a fix of this @arjantenhoopen , will make a release in a few hours.
